### PR TITLE
Fix project to work with CDK v1.62

### PR DESCRIPTION
**Pull request by mlafeldt**
There have been some breaking changes in the appsync package in the meantime.

### CODE REVIEW

**Comment by mlafeldt** [comment]
@dabit3 PTAL

**Comment by dabit3** [comment]
Hey, will be having a look shortly. Any chance you can also update the package.json to use the proper version to make this all work?

**Comment by mlafeldt** [comment]
> Hey, will be having a look shortly. Any chance you can also update the package.json to use the proper version to make this all work?

Sure. I've updated everything to the latest CDK release.

**Review by joshdlee — APPROVED** [review]

**Comment by dabit3** [comment]
Awesome, thanks for the pr!

**Pull request merged**
